// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgFbbKvTRDfXsESJtgw4zK4dgQ2mFVWio',
    appId: '1:747329651886:web:733d2a3c29c2f64651d93f',
    messagingSenderId: '747329651886',
    projectId: 'first-app-54b01',
    authDomain: 'first-app-54b01.firebaseapp.com',
    databaseURL: 'https://first-app-54b01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-54b01.appspot.com',
    measurementId: 'G-R0EV8YV359',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA74OPHmFmFynPd4hvXMWZgl5eGMqC875g',
    appId: '1:747329651886:android:9e8b02916899437e51d93f',
    messagingSenderId: '747329651886',
    projectId: 'first-app-54b01',
    databaseURL: 'https://first-app-54b01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-54b01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnVCPXkEgvUXuQBMF51l1yjgNEjajDp8s',
    appId: '1:747329651886:ios:a3a61288888059be51d93f',
    messagingSenderId: '747329651886',
    projectId: 'first-app-54b01',
    databaseURL: 'https://first-app-54b01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-54b01.appspot.com',
    iosBundleId: 'com.example.daftarbelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnVCPXkEgvUXuQBMF51l1yjgNEjajDp8s',
    appId: '1:747329651886:ios:1c4c75c51ba7978751d93f',
    messagingSenderId: '747329651886',
    projectId: 'first-app-54b01',
    databaseURL: 'https://first-app-54b01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-54b01.appspot.com',
    iosBundleId: 'com.example.daftarbelanja.RunnerTests',
  );
}
